### ISSUE TITLE
Setup Installer only show exit tab

### ISSUE THREAD

**Issue by anazeusMX** [eskay993/gamefiles#18]
I have problem when I try to launch the setup.exe it only show exit tab. I have tried click to both empty tab(right and left side) but it still asking for exit setup.
I have tested with other games setup.exe but doesnt have any issue at all. I cannot proceed to the next screen on the installer because it only show exit and 2 empty tab. I also try it on my windows PC and it works just fine, I can click to next and select the directory to save the game file. I think it was the steam OS was the main issue here because I already format my steam deck as well. 

- Which game are you trying to install?
SPFL 24

- What platform/distro are you trying it on (e.g. Steam Deck)?

Steam deck with latest update

![IMG_20231018_075421](https://github.com/eskay993/gamefiles/assets/101671967/3a3733f4-7221-43d0-a4c8-550e3b63c786)

**Comment by eskay993** [comment]
Hmm I have never seen that before. What happens if you click the `Tab` key? Does it select the Next button and can you then click enter on in? Might need a physical keyboard to use `Tab`. Can't remember if the Steam Deck virtual keyboard has that key.

The only thing I can thing to try is use a newer version of proton. Open the yaml file in a text editor (Notepad on Windows, or KWrite on Steam Deck) and change the wine version in the last line from `wine-ge-8-17-x86_64` to `wine-ge-8-20-x86_64`. If that works I'll update the script.

**Comment by anazeusMX** [comment]
Update : I just got home and the tab button seem doesnt do anything. I download spfl23 just now just to check if I can install it but surprisingly it have the same error. I have install spfl23 back in april and got it workingn without any issue the install works just fine but for the newest repack and spfl24 setup.exe I got same problem for both.

**Comment by eskay993** [comment]
Honestly mate, I have no idea. I would have recommended clearing Lutris and reinstalling it, but you reinstalled the whole OS, so that should do it :)

I won't have access to my Steam Deck till later this evening, so will try it on the latest SteamOS and see if I get something similar.

Can I double check, are you on any sort of beta or unstable branch for SteamOS? Or are you regular SteamOS stable?

**Comment by eskay993** [comment]
OK I've now tried again with the latest Steam OS stable, and a fresh install of Lutris and the game, and working fine for me. Not sure why you are getting this issue. 

Lutris just release a new update today that fixes a few things. Give that a go. The latest version is `0.5.14` and you can update it using the Discover app.

Try with a fresh Lutris install too. The easiest way to clear your Lutris settings and start fresh is to delete or rename this folder. Lutris will create a new folder and download everything it needs fresh. 

```
/home/deck/.var/app/net.lutris.Lutris
```

I suggest renaming the old folder so you don't lose any other games settings you have installed. That way you can revert back if needed.
