### ISSUE TITLE
please help

### ISSUE THREAD

**Issue by mak1n78** [eskay993/gamefiles#19]
**Details:**

- Which game are you trying to install?

- What platform/distro are you trying it on (e.g. Steam Deck)?

**Issue Description:**

_Please provide details of what steps you followed when the issue occurred:_

**Error Log:**

_If you got an error message, please paste the full log here (not just the error code)._

**Comment by eskay993** [comment]
Not sure why that's happening, but I've updated the script so that now it leaves it  to Lutris to download the latest version of ge-wine, rather than specify the version in the script. You must on at least v0.5.14 of Lutris for this to work, so make sure to update Lutris to the latest version if you haven't already. Give a go and let me know who it goes.
