### ISSUE TITLE
Fonts in settings apps are wrong

### ISSUE THREAD

**Issue by 3v1n0** [eskay993/gamefiles#24]
**Details:**

- Which game are you trying to install?

sp-football-life-2024

- What platform/distro are you trying it on (e.g. Steam Deck)?

Ubuntu

**Issue Description:**

_Please provide details of what steps you followed when the issue occurred:_

Installed the game via yaml, but fonts on settings are missing:

![immagine](https://github.com/eskay993/gamefiles/assets/345675/c5f3f396-089d-4f75-ac5c-69049b5af390)

**Error Log:**

_If you got an error message, please paste the full log here (not just the error code)._

**Comment by 3v1n0** [comment]
FYI while installing `allfonts` with winetriks fixed it, it's definitely an overkill.

So installing `malgun.ttf` was enough for me. Personally I got it from my steam's eFootball configuration, but I feel it can be found somewhere else too.

**Comment by eskay993** [comment]
Thanks for reporting. The script should install `unifont` for the settings app. It installs it manually rather than winetricks as I was having issues with Lutris and winetricks being inconsistent.

I did change how fonts are handled recently. Can I confirm when you downloaded the yaml? I made the change on 11 Jan, so if you downloaded the yaml before then, please try the latest. If you are already on the latest, then I will take a look at what's might be happening.

**Comment by 3v1n0** [comment]
Sorry, I didn't reply on time, but I indeed had installed from the yaml on January 16, so I had used the latest yaml for sure.

Can you try install just another font that should work (ttf only should be enough)
