### ISSUE TITLE
Reloaded-II needs an update to latest version for SH3 to work

### ISSUE THREAD

**Issue by octopuserectus** [eskay993/gamefiles#3]
Hi, thanks a lot for your work on the SH games. 

I think the newer Reloaded-II components are using .NET 7, so after they are updated automatically (but Reloaded-II won't) they will crash during starting the game and won't load the audio files. 
```Unable to load one or more of the requested types.
Could not load file or assembly 'System.Runtime, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. File not found.
````
I fixed it locally by manually updating Reloaded-II to the latest version and installing .NET 7 to the prefix. 

Please let me know if you want me to open a pull request, I don't have any experience with Lutris scripts but it looks trivial enough to update.

**Comment by eskay993** [comment]
Interesting. Thanks for flagging. Reloaded switched to .NET 7 back in Nov, so I decided to use the zip version of Reloaded since it does not auto-update itself, as opposed to the `Setup.exe` version which does. Thinking was to have better control of what is installed and not worry about future changes.

But, sounds like the components  do grab the latest versions and can cause a conflict.  

Thanks for offering a PR!.  I may first just test using `Setup.exe` again as it installs the latest version and all needed dependences in one go. Been thinking of doing that anyway.

Can I check which version of the Audio Enhancement Pack you're using? I've had trouble getting v3.0 working and have been using v2.0.7.

**Comment by octopuserectus** [comment]
You're welcome! Yeah, I assumed that was the reason. I'm not sure you can make it future proof, but auto-updating Reloaded now seems reasonable, to avoid further incompatibility with the components. 

I'm using Audio Enhancement Pack v3.0 and it seems that all the replacements are there in the log of Reloaded. I have not played extensively yet. Not sure what kind of issues you're having, but I didn't encounter any so far, passing v3.0 to your script.

**Comment by eskay993** [comment]
Had some time to test and can confirm the same issue you mentioned. The mod dependencies that Reloaded downloads when it launches except a newer version of .NET. Even if I use an older version of Audio Enhancement, the dependencies that are downloaded are newer and break.

I've updated the script to use the installer version of Reloaded, so it should in theory future proof it as it will always install the latest version and required .NET/ VC. Tested with v3.0 of Audio Enhancement and works fine. 

Thanks for flagging.
